[package]
name = "render_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0", default-features = false, features = [
    "serialize","bevy_window","x11", "bevy_render", "bevy_asset","bevy_color","bevy_core_pipeline","multi_threaded"
] }
bevy_internal = { version = "0.15", features = [ "bevy_image" ]}
bytemuck = "1.7"

[dev-dependencies]
bevy = { version = "0.15.0", default-features = false, features = [
    "dynamic_linking"
] }
